global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/terra_constellata_alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'a2a-server'
    static_configs:
      - targets: ['a2a-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'arangodb'
    static_configs:
      - targets: ['arangodb:8529']
    scrape_interval: 30s