server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: terra_constellata_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: terra_constellata
          __path__: /var/log/terra-constellata/*.log
    pipeline_stages:
      - match:
          selector: '{job="terra_constellata"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \| (?P<level>\w+) \| (?P<module>[^\|]+) \| (?P<message>.+)$'
            - labels:
                level: level
                module: module
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05'

  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="system"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\w+ \d+ \d{2}:\d{2}:\d{2}) (?P<hostname>\w+) (?P<process>[^\[]+)\[(?P<pid>\d+)\]: (?P<message>.+)$'
            - labels:
                hostname: hostname
                process: process
                pid: pid